flask_blog/posts/models.py
from datetime import datetime
from flask_blog import db
from flask_blog.posts.utils import slugify


post_tags = db.Table(
    'post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    tags = db.relationship(
        'Tag',
        secondary=post_tags,
        backref=db.backref('posts', lazy='dynamic')
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'<Tag id: {self.id}, name: {self.name}>'

flask_blog/posts/forms.py
from wtforms import Form, StringField, TextAreaField
from wtforms.validators import InputRequired


class PostForm(Form):
    title = StringField('Title', validators=[InputRequired()])
    body = TextAreaField('Body')

flask_blog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from flask_blog.config import Configuration

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config.from_object(Configuration)

    db.init_app(app)

    from flask_blog.main.views import main
    from flask_blog.posts.views import posts

    app.register_blueprint(main)
    app.register_blueprint(posts, url_prefix='/blog')

    return app

flask_blog/main/views.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('base.html', name="Name")

flask_blog/posts/views.py
from flask import Blueprint, request, current_app, redirect, url_for
from flask import render_template

from flask_blog import db
from flask_blog.posts.models import Post, Tag
from posts.forms import PostForm

posts = Blueprint('posts', __name__, template_folder='templates')


#http://localhost/blog/create
@posts.route('/create', methods=["GET", "POST"])
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            current_app.logger.exception('Something wrong')
            # kibana, sentry

        return redirect(url_for('posts.index'))
    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/')
def index():
    all_posts = Post.query.all()
    return render_template('posts/index.html', posts=all_posts)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


# http://localhost/blog/tag/python
@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

flask_blog/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    New post
{% endblock %}

{% block content %}

    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}

            <button type="submit" class="btn btn-success">Create</button>

        </form>
    </div>

{% endblock %}

flask_blog/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}
    {% if not posts %}
        <p>No posts yet.</p>
    {% endif %}
    {% for post in posts %}
        <p>
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </p>
    {% endfor %}
{% endblock %}

flask_blog/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                <span class="label label-primary">{{ tag.name }}</span>
            </a>
        {% endfor %}
    </div>
    <div class="main-content">
        {{ post.body }}
    </div>
{% endblock %}

flask_blog/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}
    <div class="post">
        {% for post in posts %}
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        {% endfor %}
    </div>
{% endblock %}

flask_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>

            {% block title %}

            {% endblock %} | Flask app

        </title>
        {#        https://getbootstrap.com/docs/4.4/getting-started/introduction/#}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>

    <body>

    	<nav class="navbar navbar-inverse">
    		<div class="container-fluid">
    			<!-- Brand and toggle get grouped for better mobile display -->
    			<div class="navbar-header">
    				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    					<span class="sr-only">Toggle navigation</span>
    					<span class="icon-bar"></span>
    					<span class="icon-bar"></span>
    					<span class="icon-bar"></span>
    				</button>
    				<a class="navbar-brand" href="{{ url_for('main.home') }}">Flask</a>
    			</div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{{ url_for('posts.index') }}">blogs<span class="sr-only">(current)</span></a></li>
                        <li class="active"><a href="{{ url_for('posts.create_post') }}">Create blog<span class="sr-only">(current)</span></a></li>
                    </ul>

                    <form class="navbar-form navbar-left">
                        <div class="form-group">
    						<input type="text" class="form-control" placeholder="Search">
    					</div>
    					<button type="submit" class="btn btn-default">Submit</button>
    				</form>

    				<ul class="nav navbar-nav navbar-right">
    					<li><a href="#">Link</a></li>
    				</ul>
    			</div><!-- /.navbar-collapse -->
    		</div><!-- /.container-fluid -->
    	</nav>

    	<div class="container">
    		<div class="row">
    			<h1>

                    {% block content_title %}

                    {% endblock %}

                </h1>

                {% block content %}

                {% endblock %}

    		</div>
    	</div>

	</body>

</html>

flask_blog/templates/index.html
{% extends 'base.html' %}

{% block title %}
	Main page
{% endblock %}

{% block content_title %}
	Main page
{% endblock %}

{% block content %}
	Something text
{% endblock %}